title: Elemen.ai Content Hub
description: Drafts for AI-Generated Content
baseurl: "/elemen-ai-content" # Leave empty unless you're serving from a subpath
url: "https://sateayamsuper.github.io" # No trailing slash

theme: jekyll-theme-cayman

markdown: kramdown
plugins:
  - jekyll-feed
