# _config.yml
title: Elemen.ai Content Hub
description: Drafts for AI-Generated Content
url: "https://sateayamsuper.github.io"
baseurl: "/elemen-ai-content"

theme: jekyll-theme-primer     
plugins:
  - jekyll-feed
