title: Elemen.ai Content Hub
description: AI-generated marketing drafts and posts
baseurl: "/elemen-ai-content"      # leave empty for https://<user>.github.io/elemen-content
url: "https://sateayamsuper.github.io/elemen-ai-content/"
theme: minimal-mistakes-jekyll

# Enable collections, plugins, and extras
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true

minimal_mistakes_skin: "modern"
